#License: https://techexpert.tips/elasticsearch/filebeat-sending-syslog-messages-elasticsearch/
filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/syslog
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "192.168.1.13:5601"
output.elasticsearch:
  hosts: ["192.168.1.13:9200"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~